@WordFinder_HostAddress = https://localhost:5001

POST {{WordFinder_HostAddress}}/api/WordFinder
Accept: application/json
Content-Type: application/json
{
  "matrix": [
    "abcdc",
    "fgwio",
    "chill",
    "ponsd",
    "ptnsd",
    "sadxy"
  ],
  "wordstream": [
    "chill",
    "hot",
    "wind"
  ]
}